services:
  frontend:
    build:
      context: ./frontend
      args:
        # This sends the values to the Dockerfile during 'npm run build'
        - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
        - NEXT_PUBLIC_WS_URL=${NEXT_PUBLIC_WS_URL}
        - PROJECT_NAME=${PROJECT_NAME}
    environment:
      # This makes them available if you use Server-Side Rendering (SSR)
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
      - NEXT_PUBLIC_WS_URL=${NEXT_PUBLIC_WS_URL}
    container_name: ${PROJECT_NAME}-frontend
    networks:
      - web-gateway

  api-server:
    build: ./api-server
    container_name: ${PROJECT_NAME}-api-server
    environment:
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
    networks:
      - web-gateway

  ws-server:
    build: ./ws-server
    container_name: ${PROJECT_NAME}-ws-server
    networks:
      - web-gateway

networks:
  web-gateway:
    external: true
